### ISSUE TITLE
Running callKit tasks when app is terminated

### ISSUE THREAD

**Issue by andreassh** [Taracque/cordova-plugin-voippush#3]
Hi there,

Thank you for a great plugin.

I'm using voip push to call callKit and prompt the native incoming call screen.
This works fine if the app is open or in the background.
However, if i terminate the app and report an incoming call through call kit, nothing happens. 
I can see in my logs that my JS is executed, by the incoming call screen doesn't prompt.

The weird thing is that, if i debug my ionic app (through safari), while sending the voip push, the call screen prompts as expected even when the app is terminated. 

Any ideas, on why that is?

**Comment by Taracque** [comment]
Are VoIP and Background Fetch and Remote Notification background modes are all turned on?

**Comment by andreassh** [comment]
Yes. This is the enabled capabilities: 
<img width="724" alt="screen shot 2017-08-03 at 09 52 13" src="https://user-images.githubusercontent.com/1119754/28911663-8e57c0e4-7831-11e7-8fac-67c4c88e6d0f.png">

**Comment by andreassh** [comment]
So I figured it out. I was reporting an incomingcall before callkit was properly init'ed . sorry about that. closing now.
